_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 37.108
  - -1.0874
  - 12
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 0
name: ''
source: "tmsource://c:/Work/KMP_PROJECT/KMP_project/mapbox_Styles/Thika/Thika.tm2source"
styles: 
  - style.mss
template: ''
